fix AttributeError in Application.validade_quit()
Error:
  self.get_window().quit()
  AttributeError: 'Application' object has no attribute 'get_window'

Note on MainWindow.do_delete_event:
    - returning True: aborts the default behaviour from Super Class (so it does NOT close
    the window)
    - returning False: keeps the default, which closes that window